name: Verify Build Workflow
on:
  push:
    paths-ignore:
      - '.dockerignore'
      - '.gitignore'
      - 'README*'
    branches: [main]
  pull_request:
    paths-ignore:
      - '.dockerignore'
      - '.gitignore'
      - 'README*'
    branches: [main]

jobs:
  verify-build:
    name: Verify Build
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'shareNwork'
    steps:
      - name: Checkout Code with Ref '${{ github.ref }}'
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64

      - name: Get maven wrapper
        run: mvn -N io.takari:maven:wrapper -Dmaven=3.6.3

      - name: Build Project
        run: ./mvnw clean install
